<?php

namespace App\Model;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Question extends Model
{
    protected $fillable = ['title', 'slug', 'body', 'category_id', 'user_id'];
    //change key from id to slug
    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    //relation with user
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    //relation with replies
    public function replies()
    {
        return $this->hasMany(Reply::class);
    }
    //relation with category
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    //path function
    public function getPathAttribute() {
        return asset("api/questions/$this->slug");
    }
}
